// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: models/message.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CyDrive.Models {

  /// <summary>Holder for reflection information generated from models/message.proto</summary>
  public static partial class MessageReflection {

    #region Descriptor
    /// <summary>File descriptor for models/message.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRtb2RlbHMvbWVzc2FnZS5wcm90bxIGbW9kZWxzGh9nb29nbGUvcHJvdG9i",
            "dWYvdGltZXN0YW1wLnByb3RvGhJjb25zdHMvZW51bXMucHJvdG8iqgEKB01l",
            "c3NhZ2USCgoCaWQYASABKAMSDgoGc2VuZGVyGAIgASgFEhAKCHJlY2VpdmVy",
            "GAMgASgFEiEKBHR5cGUYBCABKA4yEy5jb25zdHMuTWVzc2FnZVR5cGUSDwoH",
            "Y29udGVudBgFIAEoCRItCglzZW5kZWRfYXQYBiABKAsyGi5nb29nbGUucHJv",
            "dG9idWYuVGltZXN0YW1wEg4KBkV4cGlyZRgHIAEoBUIsWhlnaXRodWIuY29t",
            "L0N5RHJpdmUvbW9kZWxzqgIOQ3lEcml2ZS5Nb2RlbHNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::CyDrive.EnumsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CyDrive.Models.Message), global::CyDrive.Models.Message.Parser, new[]{ "Id", "Sender", "Receiver", "Type", "Content", "SendedAt", "Expire" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Message : pb::IMessage<Message> {
    private static readonly pb::MessageParser<Message> _parser = new pb::MessageParser<Message>(() => new Message());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Message> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CyDrive.Models.MessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Message() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Message(Message other) : this() {
      id_ = other.id_;
      sender_ = other.sender_;
      receiver_ = other.receiver_;
      type_ = other.type_;
      content_ = other.content_;
      sendedAt_ = other.sendedAt_ != null ? other.sendedAt_.Clone() : null;
      expire_ = other.expire_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Message Clone() {
      return new Message(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "sender" field.</summary>
    public const int SenderFieldNumber = 2;
    private int sender_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Sender {
      get { return sender_; }
      set {
        sender_ = value;
      }
    }

    /// <summary>Field number for the "receiver" field.</summary>
    public const int ReceiverFieldNumber = 3;
    private int receiver_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Receiver {
      get { return receiver_; }
      set {
        receiver_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 4;
    private global::CyDrive.MessageType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CyDrive.MessageType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "content" field.</summary>
    public const int ContentFieldNumber = 5;
    private string content_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Content {
      get { return content_; }
      set {
        content_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sended_at" field.</summary>
    public const int SendedAtFieldNumber = 6;
    private global::Google.Protobuf.WellKnownTypes.Timestamp sendedAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp SendedAt {
      get { return sendedAt_; }
      set {
        sendedAt_ = value;
      }
    }

    /// <summary>Field number for the "Expire" field.</summary>
    public const int ExpireFieldNumber = 7;
    private int expire_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Expire {
      get { return expire_; }
      set {
        expire_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Message);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Message other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Sender != other.Sender) return false;
      if (Receiver != other.Receiver) return false;
      if (Type != other.Type) return false;
      if (Content != other.Content) return false;
      if (!object.Equals(SendedAt, other.SendedAt)) return false;
      if (Expire != other.Expire) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (Sender != 0) hash ^= Sender.GetHashCode();
      if (Receiver != 0) hash ^= Receiver.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      if (Content.Length != 0) hash ^= Content.GetHashCode();
      if (sendedAt_ != null) hash ^= SendedAt.GetHashCode();
      if (Expire != 0) hash ^= Expire.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Sender != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Sender);
      }
      if (Receiver != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Receiver);
      }
      if (Type != 0) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Type);
      }
      if (Content.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Content);
      }
      if (sendedAt_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(SendedAt);
      }
      if (Expire != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Expire);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (Sender != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Sender);
      }
      if (Receiver != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Receiver);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Content.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Content);
      }
      if (sendedAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SendedAt);
      }
      if (Expire != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Expire);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Message other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.Sender != 0) {
        Sender = other.Sender;
      }
      if (other.Receiver != 0) {
        Receiver = other.Receiver;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.Content.Length != 0) {
        Content = other.Content;
      }
      if (other.sendedAt_ != null) {
        if (sendedAt_ == null) {
          sendedAt_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        SendedAt.MergeFrom(other.SendedAt);
      }
      if (other.Expire != 0) {
        Expire = other.Expire;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 16: {
            Sender = input.ReadInt32();
            break;
          }
          case 24: {
            Receiver = input.ReadInt32();
            break;
          }
          case 32: {
            type_ = (global::CyDrive.MessageType) input.ReadEnum();
            break;
          }
          case 42: {
            Content = input.ReadString();
            break;
          }
          case 50: {
            if (sendedAt_ == null) {
              sendedAt_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(sendedAt_);
            break;
          }
          case 56: {
            Expire = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
